use raps
truncate table clients
truncate table client_contacts
truncate table locations
truncate table applications
truncate table rating
truncate table rating_liability
truncate table rating_liability_otherexp
truncate table rating_liability_debtcredits
truncate table rating_property
truncate table policy_info
truncate table epli_consolidation
truncate table ue_consolidation
truncate table wc_consolidation
truncate table client_wc